@echo off
REM setup-env.bat — local Windows script to write backend\.env with real values.
REM This file is NEVER committed (see .gitignore).

cd /d "%~dp0"
if not exist "backend" mkdir backend

set "SUPABASE_URL=https://gucphxniwuarubrrcoms.supabase.co"
set "SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1Y3BoeG5pd3VhcnVicnJjb21zIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjMzNDkxMCwiZXhwIjoyMTAxOTEwOTEwfQ.fdRZjlD8ndP3o-jM6PXdw42xD5lGD5fZn0TUbNTRE_A"
set "SUPABASE_STORAGE_BUCKET=invoices"

(
  echo # Generated by setup-env.bat — LOCAL ONLY, do NOT commit.
  echo SUPABASE_URL=%SUPABASE_URL%
  echo SUPABASE_SERVICE_ROLE_KEY=%SUPABASE_SERVICE_ROLE_KEY%
  echo SUPABASE_STORAGE_BUCKET=%SUPABASE_STORAGE_BUCKET%
  echo.
  echo SMTP_HOST=
  echo SMTP_PORT=587
  echo SMTP_USERNAME=
  echo SMTP_PASSWORD=
  echo SMTP_FROM_EMAIL=
  echo SMTP_FROM_NAME=Invoice System
  echo SMTP_ENCRYPTION=TLS
  echo.
  echo FRONTEND_URL=http://localhost:5173
  echo PAYMENT_REMINDER_CHECK_INTERVAL_MINUTES=60
) > backend\.env

echo Wrote backend\.env
echo.
echo Next:
echo   1. cd backend
echo   2. pip install -r requirements.txt
echo   3. uvicorn app.main:app --reload --port 8000
echo   4. Open http://localhost:8000/api/health
