#!/usr/bin/env bash
# setup-env.sh
# Local-only script that writes backend/.env with your real Supabase credentials.
# This file is NEVER committed to git (see .gitignore).
#
# Usage:
#   chmod +x setup-env.sh
#   ./setup-env.sh
set -euo pipefail

cd "$(dirname "$0")"
mkdir -p backend

# --- Your real Supabase project values (LOCAL ONLY, not committed) ---
export SUPABASE_URL="https://gucphxniwuarubrrcoms.supabase.co"
export SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1Y3BoeG5pd3VhcnVicnJjb21zIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjMzNDkxMCwiZXhwIjoyMTAxOTEwOTEwfQ.fdRZjlD8ndP3o-jM6PXdw42xD5lGD5fZn0TUbNTRE_A"
export SUPABASE_STORAGE_BUCKET="invoices"

cat > backend/.env <<EOF
# Generated by setup-env.sh — LOCAL ONLY, do NOT commit.
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
SUPABASE_STORAGE_BUCKET=${SUPABASE_STORAGE_BUCKET}

# SMTP (optional — fill in to actually send emails)
SMTP_HOST=
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=
SMTP_FROM_NAME=Invoice System
SMTP_ENCRYPTION=TLS

FRONTEND_URL=http://localhost:5173
PAYMENT_REMINDER_CHECK_INTERVAL_MINUTES=60
EOF

echo "Wrote backend/.env"
echo ""
echo "Next:"
echo "  1. cd backend && pip install -r requirements.txt"
echo "  2. uvicorn app.main:app --reload --port 8000"
echo "  3. Open http://localhost:8000/api/health"
